"""
Notso.ai mascot style lock for image generation pipeline.

Every image generation call in generate.py / the notso-proposal-gen backend
MUST go through build_style_prompt() so that the rules documented in
notso_style_lock.md are enforced at the prompt layer. Nothing generated by
this system bypasses this module.

Locked: 2026-04-12  (v1.0)
"""

STYLE_VERSION = "1.0"

# -----------------------------------------------------------------------------
# Core style prefix. Prepended to every positive prompt.
# -----------------------------------------------------------------------------
STYLE_PREFIX = (
    "A 3D-rendered character in the distinctive Notso AI signature style. "
    "Matte clay and vinyl designer-toy finish, smooth even surface, no gloss, "
    "no plastic shine, no metallic reflection. "
    "Soft three-point studio lighting with a warm key light from upper "
    "camera-left, a low-intensity fill from the right, and a single thin rim "
    "light on the silhouette. "
    "Large round eyes with a solid black pupil and one small white highlight "
    "point — no iris detail, no eyelashes, no catchlight shapes. "
    "Thick, dark, prominent eyebrows that carry the emotion. "
    "No hard black outlines; silhouette is defined by form and rim light. "
    "Fully transparent background (PNG with alpha channel, no baked backdrop). "
    "Character is centered, full body visible, slight low-angle hero framing. "
)

# -----------------------------------------------------------------------------
# Negative prompt. Appended to every generation call.
# -----------------------------------------------------------------------------
NEGATIVE_SUFFIX = (
    "blurry, low quality, distorted, extra limbs, extra fingers, malformed "
    "hands, hard black outlines, cel shading, anime, manga, comic speed lines, "
    "cyberpunk, Y2K, metallic finish, chrome, neon glow, holographic, "
    "plastic shine, glossy surface, glass refraction, "
    "realistic skin pores, realistic hair strands, photorealistic human, "
    "stop-motion texture, clay thumbprints, visible sculpting marks, "
    "fur strand simulation, hard cast shadows, dramatic contrast, "
    "firearms, guns, weapons, knives, "
    "religious symbols, crosses, crescents, stars of david, halos, "
    "nudity, revealing clothing, underwear, "
    "political symbols, political flags, "
    "cigarettes, smoking, alcohol, beer, wine, "
    "brand logo on skin, text on face, tattoos on face, "
    "baked background, cream grid, pastel card, studio backdrop, "
    "colored backdrop, vignette, drop shadow baked in, ground shadow, "
    "multiple characters unless requested, watermark, signature, frame, border"
)

# -----------------------------------------------------------------------------
# Proportion tier modifiers.
# -----------------------------------------------------------------------------
HERO_TIER_MODIFIER = (
    "Adult stylized proportions, head-to-body ratio approximately 1 to 2, "
    "defined shoulders and posture, hands capable of holding objects and "
    "performing precise gestures. "
)

CHIBI_TIER_MODIFIER = (
    "Chibi toy proportions, head-to-body ratio approximately 1 to 1.4, "
    "oversized head, short stubby limbs, designer vinyl collectible "
    "silhouette reminiscent of blind-box figures but with a distinctive "
    "Notso AI face. "
)

# -----------------------------------------------------------------------------
# Mood modifiers.
# -----------------------------------------------------------------------------
MOOD_FRIENDLY = (
    "Friendly welcoming pose, subtle smile, eye contact with camera, "
    "relaxed shoulders. "
)

MOOD_MOODY = (
    "Moody variant: single low-angle warm key light, contemplative posture, "
    "subtle desaturation on wardrobe, eyebrows angled for worry or focus. "
    "Transparent background still — do not bake a dark backdrop. "
)

MOOD_CELEBRATE = (
    "Celebratory pose, arms raised or one fist up, bright wide smile, "
    "eyebrows raised, energetic stance. "
)

MOOD_THINKING = (
    "Thinking pose, one hand near chin or temple, eyes slightly up, "
    "eyebrows gently furrowed, mouth in a small neutral line. "
)

_MOOD_MAP = {
    "friendly": MOOD_FRIENDLY,
    "moody": MOOD_MOODY,
    "celebrate": MOOD_CELEBRATE,
    "thinking": MOOD_THINKING,
}

# -----------------------------------------------------------------------------
# Species modifiers.
# -----------------------------------------------------------------------------
def _species_line(species: str) -> str:
    s = species.lower().strip()
    if s in ("human", "humanoid", "person", "level1", "1"):
        return (
            "Humanoid character, stylized person, neutral warm skin tone "
            "(beige / peach / light brown / tan). "
        )
    if s in ("animal", "personified animal", "level2", "2"):
        return (
            "Personified animal character with humanlike posture and clothing. "
            "Natural neutral fur or hide colour (white, grey, brown, tan, "
            "cream) — brand colour lives on clothing only, never on fur. "
        )
    if s in ("object", "personified object", "level3", "3"):
        return (
            "Personified object character — an everyday object brought to "
            "life with a simple face, small hands, and small feet, while "
            "keeping its original shape and base colour. "
        )
    if s in ("abstract", "pure abstract", "level4", "4"):
        raise ValueError(
            "Level 4 (pure abstract form) is disallowed by the Notso AI "
            "style lock v1.0. Use Level 3 (personified object) instead — "
            "e.g. 'a lightbulb with a face, arms, and legs' rather than "
            "'a bolt of light'."
        )
    # default fallback = humanoid
    return (
        "Humanoid character, stylized person, neutral warm skin tone. "
    )

# -----------------------------------------------------------------------------
# Global negatives that cannot be overridden by callers.
# -----------------------------------------------------------------------------
GLOBAL_FORBIDDEN_IDENTITIES = (
    "Never depict the character as a robot, cyborg, or artificial intelligence. "
    "The character is a digital colleague, not a machine. "
)

# -----------------------------------------------------------------------------
# Style transfer modifier — used when the client has an existing mascot and
# wants it re-rendered in Notso style. Turns the pipeline from "create a fresh
# character" into "translate this character into Notso style while preserving
# identity". Paired with a reference image in the Gemini call.
# -----------------------------------------------------------------------------
STYLE_TRANSFER_MODIFIER = (
    "STYLE TRANSFER MODE: The attached reference image is the client's "
    "existing mascot. Re-render this exact character in the Notso AI "
    "signature style described above. PRESERVE CHARACTER IDENTITY "
    "(silhouette, body shape, species, facial structure, head accessories, "
    "colour identity) — the output must be immediately recognisable as the "
    "same character. Only change the rendering: apply Notso matte clay / "
    "vinyl finish, Notso eye formula (solid pupil + one highlight, no iris), "
    "Notso eyebrows, Notso three-point lighting, transparent PNG background. "
    "Do NOT generate a new unrelated character. Do NOT copy the reference "
    "background. Do NOT add extra characters. "
)

# -----------------------------------------------------------------------------
# Main builder — every generation call goes through this.
# -----------------------------------------------------------------------------
def build_style_prompt(
    character_description: str,
    brand_color_name: str,
    tier: str = "hero",
    species: str = "human",
    mood: str = "friendly",
    accent_color_name: str | None = None,
    style_transfer: bool = False,
) -> tuple[str, str]:
    """
    Build the final (positive_prompt, negative_prompt) pair for one image.

    Parameters
    ----------
    character_description : str
        Free-text description of who the character is (name, role, outfit
        details beyond the brand vest, props, etc.).
    brand_color_name : str
        Human-readable colour name. e.g. "vivid red", "forest green",
        "royal blue", "sunflower yellow". Not a hex code — the model reads
        words better than numbers here.
    tier : str
        "hero" for adult proportions, "chibi" for toy proportions.
    species : str
        "human" | "animal" | "object" | "abstract"
        (also accepts "level1" .. "level4" as aliases).
    mood : str
        "friendly" | "moody" | "celebrate" | "thinking".
    accent_color_name : str | None
        Optional second brand colour for accents (e.g. scarf, shoelaces).
    style_transfer : bool
        If True, appends STYLE_TRANSFER_MODIFIER to preserve an attached
        reference image's identity. Pair with a reference image in the
        actual generation call.

    Returns
    -------
    (positive_prompt, negative_prompt) : tuple[str, str]
    """
    tier_mod = HERO_TIER_MODIFIER if tier.lower() == "hero" else CHIBI_TIER_MODIFIER
    species_mod = _species_line(species)
    mood_mod = _MOOD_MAP.get(mood.lower(), MOOD_FRIENDLY)

    if accent_color_name:
        color_line = (
            f"Wardrobe and accessories use a single {brand_color_name} "
            f"signature colour with a {accent_color_name} accent. "
            "Skin, fur, and hair stay neutral — brand colour does NOT "
            "appear on the body itself. "
        )
    else:
        color_line = (
            f"Wardrobe and accessories use a single {brand_color_name} "
            "signature colour. Skin, fur, and hair stay neutral — brand "
            "colour does NOT appear on the body itself. "
        )

    transfer_line = STYLE_TRANSFER_MODIFIER if style_transfer else ""

    positive = (
        STYLE_PREFIX
        + tier_mod
        + species_mod
        + color_line
        + mood_mod
        + GLOBAL_FORBIDDEN_IDENTITIES
        + transfer_line
        + "Character: "
        + character_description.strip()
    )
    return positive, NEGATIVE_SUFFIX


# -----------------------------------------------------------------------------
# Convenience: pre-baked prompts for the existing reference cast.
# Used for regression testing the style lock against known-good outputs.
# -----------------------------------------------------------------------------
REFERENCE_CAST = {
    "fin": dict(
        character_description=(
            "Fin, a financial expert for a sports club. Brown swept-back hair, "
            "near-black thick eyebrows, dark eyes, warm friendly smile. "
            "Wears a red vest with a small white 'Fin' name tag over a white "
            "long-sleeve shirt and dark trousers. "
        ),
        brand_color_name="vivid red",
        tier="hero",
        species="human",
        mood="friendly",
    ),
    "willy": dict(
        character_description=(
            "Willy, an ergonomic-chair sales assistant. Curly light-brown "
            "hair under a green bucket hat with a white '7' on it. Green "
            "cardigan over a light scarf, cream trousers, white sneakers. "
        ),
        brand_color_name="forest green",
        accent_color_name="cream",
        tier="hero",
        species="human",
        mood="friendly",
    ),
    "woof": dict(
        character_description=(
            "Woof, a university student buddy. A friendly husky with grey "
            "and white fur, large black eyes, tiny yellow cheek blush dots, "
            "wearing a royal-blue hoodie with a 'Sarajevo University' logo "
            "across the chest and a small backpack strap visible. "
        ),
        brand_color_name="royal blue",
        accent_color_name="bright yellow",
        tier="chibi",
        species="animal",
        mood="friendly",
    ),
}


def reference_prompt(name: str) -> tuple[str, str]:
    """Return the canonical prompt pair for a known cast member."""
    spec = REFERENCE_CAST[name.lower()]
    return build_style_prompt(**spec)


if __name__ == "__main__":
    # Smoke test — print the Fin prompt so humans can eyeball the lock.
    pos, neg = reference_prompt("fin")
    print("=" * 72)
    print("POSITIVE PROMPT")
    print("=" * 72)
    print(pos)
    print()
    print("=" * 72)
    print("NEGATIVE PROMPT")
    print("=" * 72)
    print(neg)
