#!/usr/bin/env python3
"""
Zip the asset pack directory and add an overview.html file.

Usage: python3 zip_assetpack.py <src_dir> <out_zip>

Expects <src_dir> to contain:
  - manifest.json  (with clientName, mascotName, brandColor, results[])
  - expressions/*.png
  - actions/*.png
  - festive/*.png
  - mockups/*.png
"""
import json
import os
import sys
import zipfile
import html


def build_overview_html(manifest, src_dir):
    client = html.escape(manifest.get("clientName", "Client"))
    mascot = html.escape(manifest.get("mascotName", "Mascot"))
    brand = html.escape(manifest.get("brandColor", "#0068B7"))
    generated = html.escape(manifest.get("generatedAt", ""))
    results = manifest.get("results", [])

    # Group by category
    by_cat = {}
    for r in results:
        by_cat.setdefault(r.get("category", "other"), []).append(r)

    category_order = ["expressions", "actions", "festive", "mockups", "other"]
    category_labels = {
        "expressions": "Expressions",
        "actions": "Actions",
        "festive": "Festive",
        "mockups": "Mockups",
        "other": "Other",
    }

    sections = []
    for cat in category_order:
        if cat not in by_cat:
            continue
        items = by_cat[cat]
        tiles = []
        for r in items:
            label = html.escape(r.get("label", ""))
            if r.get("ok") and r.get("file"):
                rel = html.escape(r["file"])
                tiles.append(
                    f'<figure><div class="thumb"><img src="{rel}" alt="{label}"/></div>'
                    f'<figcaption>{label}</figcaption></figure>'
                )
            else:
                err = html.escape(str(r.get("error", "unknown error")))
                tiles.append(
                    f'<figure class="failed"><div class="thumb">⚠️</div>'
                    f'<figcaption>{label}<br><small>{err}</small></figcaption></figure>'
                )
        sections.append(
            f'<section><h2>{category_labels.get(cat, cat.title())}</h2>'
            f'<div class="grid">{"".join(tiles)}</div></section>'
        )

    html_out = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>{client} — Mascot Asset Pack ({mascot})</title>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<style>
  :root {{ --accent: {brand}; --bg: #FAFAF6; --ink: #0B0B0B; --muted: #6B7280; --line: #E5E7EB; }}
  * {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; background: var(--bg); color: var(--ink); margin: 0; padding: 40px 20px; }}
  .wrap {{ max-width: 1200px; margin: 0 auto; }}
  header {{ border-bottom: 2px solid var(--line); padding-bottom: 24px; margin-bottom: 32px; }}
  header h1 {{ font-size: 32px; margin: 0 0 6px; letter-spacing: -0.6px; }}
  header .sub {{ color: var(--muted); font-size: 14px; }}
  header .chip {{ display: inline-block; background: var(--accent); color: #fff; padding: 3px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; margin-left: 8px; }}
  section {{ margin-bottom: 40px; }}
  section h2 {{ font-size: 20px; margin: 0 0 16px; display: flex; align-items: center; gap: 10px; }}
  section h2::before {{ content: ""; width: 4px; height: 18px; background: var(--accent); border-radius: 2px; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 16px; }}
  figure {{ margin: 0; background: #fff; border: 1px solid var(--line); border-radius: 14px; overflow: hidden; transition: transform 0.15s, box-shadow 0.15s; }}
  figure:hover {{ transform: translateY(-2px); box-shadow: 0 8px 24px rgba(0,0,0,0.08); }}
  figure.failed {{ background: #FEF2F2; border-color: #FCA5A5; }}
  .thumb {{ aspect-ratio: 1; display: flex; align-items: center; justify-content: center; background: repeating-conic-gradient(#F3F4F6 0 25%, #fff 0 50%) 50% / 20px 20px; font-size: 32px; }}
  .thumb img {{ max-width: 100%; max-height: 100%; object-fit: contain; display: block; }}
  figcaption {{ padding: 10px 12px; font-size: 12px; font-weight: 600; text-align: center; color: var(--ink); border-top: 1px solid var(--line); }}
  figcaption small {{ display: block; color: var(--muted); font-weight: 400; margin-top: 2px; }}
  footer {{ margin-top: 40px; padding-top: 24px; border-top: 1px solid var(--line); color: var(--muted); font-size: 12px; text-align: center; }}
</style>
</head>
<body>
  <div class="wrap">
    <header>
      <h1>{client} — {mascot} Asset Pack <span class="chip">notso.ai</span></h1>
      <div class="sub">Mascot expressions, actions, festive variants, and mockups · Generated {generated}</div>
    </header>
    {''.join(sections)}
    <footer>
      Powered by notso.ai · All images generated by Gemini AI based on your selected mascot
    </footer>
  </div>
</body>
</html>
"""
    return html_out


def main():
    if len(sys.argv) != 3:
        print("Usage: zip_assetpack.py <src_dir> <out_zip>", file=sys.stderr)
        sys.exit(1)

    src_dir = sys.argv[1]
    out_zip = sys.argv[2]

    manifest_path = os.path.join(src_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        print(f"manifest.json not found in {src_dir}", file=sys.stderr)
        sys.exit(1)

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    overview_html = build_overview_html(manifest, src_dir)
    overview_path = os.path.join(src_dir, "overview.html")
    with open(overview_path, "w", encoding="utf-8") as f:
        f.write(overview_html)

    # Walk src_dir and add all files to zip, preserving subfolders
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, _dirs, files in os.walk(src_dir):
            for name in files:
                full = os.path.join(root, name)
                rel = os.path.relpath(full, src_dir)
                zf.write(full, rel)

    print(f"OK {out_zip}")


if __name__ == "__main__":
    main()
